# See https://pre-commit.com for more information
# See https://pre-commit.com/hooks.html for more hooks
repos:
    -   repo: https://github.com/pre-commit/pre-commit-hooks
        rev: v3.2.0
        hooks:
            - id: trailing-whitespace
            - id: end-of-file-fixer
            - id: check-yaml
            - id: check-added-large-files
    -   repo: local
        hooks:
            - id: isort
              name: foramtting::isort
              entry: poetry run isort
              language: system
              types: [python]
            - id: black
              name: foramtting::black
              entry: poetry run black
              language: system
              types: [python]
    -   repo: local
        hooks:
            - id: flake8
              name: linting::flake8
              entry: poetry run flake8
              language: system
              types: [python]
    -   repo: https://github.com/aws-cloudformation/cfn-python-lint
        rev: v0.61.1
        hooks:
        - id: cfn-python-lint
          files: template.yaml
